name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  IMAGE_VERSION: "v0.1.6"
  SSH_USER: "${{ secrets.SSH_USER }}"
  SSH_HOST: "${{ secrets.SSH_HOST }}"
  SSH_PASSWORD: "${{ secrets.SSH_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login Aliyun
        run: 
          docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
      -
        name: Build and Push
        run: |
          docker build -t $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/xh-blog:$IMAGE_VERSION .
          docker tag $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/xh-blog:$IMAGE_VERSION $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/xh-blog:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/xh-blog:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/xh-blog:$IMAGE_VERSION
          docker pull mysql
          docker tag mysql:latest $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/mysql:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/mysql:latest
          docker pull redis
          docker tag redis:latest $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/redis:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/redis:latest
          docker pull nginx
          docker tag nginx:latest $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest
          docker pull mongo
          docker tag mongo:latest $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/mongo:latest
          docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/mongo:latest
      - 
        name: deploy
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker-compose pull && docker-compose up -d"
          



       